name: LaunchingSecrets

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  test_schedule:
    runs-on: ubuntu-latest
    steps:
      - uses: oNaiPs/secrets-to-env-action@v1
        with: 
          secrets: ${{ toJSON(secrets) }}
